import type { Metadata } from "next";
import "the-new-css-reset/css/reset.css";
import "./globals.css";
import { Header } from "@/components/header";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <Header />
        <div
          style={{
            maxWidth: "80ch",
            marginInline: "auto",
            padding: 20,
          }}
        >
          {children}
        </div>
      </body>
    </html>
  );
}
